in:
  type: file
  path_prefix: ./sample/csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: 
  type: file 
  path_prefix: ./sample/result
  file_ext: csv.gpg
  formatter:
    type: csv
  encoders:
    - type: pgp_encryption
      public_key_ring: ./sample/pubring.gpg
      key_name: mokemokechicken@gmail.com
